apiVersion: apps/v1
kind: Deployment
metadata:
  name: starscan-sub-deployment
  namespace: starcoin-halley
  labels:
    app: starscan-sub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: starscan-sub
  template:
    metadata:
      labels:
        app: starscan-sub
    spec:
      containers:
        - name: starscan-sub
          image: starcoin/starcoin_scan_sub:sha-0af24fa
          ports:
            - containerPort: 8200
          env:
            - name: HOSTS
              value: "halley1.seed.starcoin.org,halley2.seed.starcoin.org,halley3.seed.starcoin.org"
            - name: NETWORK
              value: "halley"
            - name: STARCOIN_ES_URL
              value: "search-starcoin-es2-47avtmhexhbg7qtynzebcnnu64.ap-northeast-1.es.amazonaws.com"
            - name: STARCOIN_ES_PROTOCOL
              value: "https"
            - name: STARCOIN_ES_PORT
              value: "443"
            - name: STARCOIN_ES_USER
              value: elastic
            - name: STARCOIN_ES_PWD
              valueFrom:
                secretKeyRef:
                  name: elasticsearch-pw-elastic
                  key: password
